=== usnistgov/v2-validation/validation/src/main/resources/rules/ValueSets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 3 (x64) (http://www.altova.com) by ww (NIST) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="ValueSetLibrary">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MetaData" type="MetaDataType" minOccurs="1" maxOccurs="1"/>
				<xs:element name="NoValidation" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="BindingIdentifier" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ValueSetDefinitions" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ValueSetDefinition" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="ValueElement">
											<xs:complexType>
												<xs:attribute name="Value" type="xs:string"
												use="required"/>
												<xs:attribute name="DisplayName" type="xs:string"
												use="required"/>
												<xs:attribute name="CodeSystem" type="xs:string"
												use="optional"/>
												<xs:attribute name="CodeSystemVersion"
												type="xs:string" use="optional"/>
												<xs:attribute name="Usage" type="UsageType"
												use="optional" default="R"/>
												<xs:attribute name="Comments" type="xs:string"
												use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="BindingIdentifier" type="xs:string"
										use="required"/>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="Description" type="xs:string" use="optional"/>
									<xs:attribute name="Version" type="xs:string" use="optional"/>
									<xs:attribute name="Oid" type="xs:string"/>
									<xs:attribute name="Stability" type="StabilityType"
										use="optional"/>
									<xs:attribute name="Extensibility" type="ExtensibilityType"
										use="optional"/>
									<xs:attribute name="ContentDefinition"
										type="ContentDefinitionType" use="optional"/>
									<xs:attribute name="NoCodeDisplayText"
										type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Group" type="xs:string"/>
						<xs:attribute name="Order" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ValueSetLibraryIdentifier" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="StabilityType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Static"/>
			<xs:enumeration value="Dynamic"/>
			<xs:enumeration value="Undefined"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExtensibilityType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Open"/>
			<xs:enumeration value="Closed"/>
			<xs:enumeration value="Undefined"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ContentDefinitionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Extensional"/>
			<xs:enumeration value="Intensional"/>
			<xs:enumeration value="Undefined"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UsageType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="R"/>
			<xs:enumeration value="P"/>
			<xs:enumeration value="E"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NonEmptyString">
		<xs:restriction base="xs:string">
			<xs:pattern value="[\s]*[\S].*"/>
			<!-- \S is the negation of \s  -->
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="MetaDataType">
		<xs:attribute name="Name" type="NonEmptyString" use="required">
			<xs:annotation>
				<xs:documentation>Name of this ValueSets ex) ValueSet for VXU-Z22/_Profile.xml</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="OrgName" type="NonEmptyString" use="required">
			<xs:annotation>
				<xs:documentation>Organization Name of this ValueSets ex) NIST</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Version" type="NonEmptyString" use="required">
			<xs:annotation>
				<xs:documentation>Version of this ValueSets ex) 1.0.0</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Date" type="NonEmptyString" use="required">
			<xs:annotation>
				<xs:documentation>Date of this ValueSets ex) YYYYMMDD</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="SpecificationName" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Provides a name that clearly and concisely defines the valuesets being listed.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Status" use="optional">
			<xs:annotation>
				<xs:documentation>Status of this ValueSets, as assigned by the author. There is no prescribed status scheme at this time. Possible values might include: 'Draft', 'Active', 'Superceded', 'Withdrawn'</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Draft"/>
					<xs:enumeration value="Active"/>
					<xs:enumeration value="Superceded"/>
					<xs:enumeration value="Withdrawn"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Topics" type="NonEmptyString" use="optional">
			<xs:annotation>
				<xs:documentation>This provides a list of key-words that relate to the ValueSets and that may be useful in valueset searches.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== usnistgov/v2-validation/validation/src/test/resources/ValueSets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 3 (x64) (http://www.altova.com) by ww (NIST) -->
<ValueSetLibrary  
    ValueSetIdentifier=""
	Description="Automatically generated vacab for ACK"
	Name="Vocab for ACK"
	OrganizationName="HL7 NIST"
	Status="Active"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../main/resources/vs/ValueSets.xsd">

    <NoValidation>
        <BindingIdentifier>0396</BindingIdentifier>
        <!--<id>HL70533_IZ</id>
        <id>HL70301_IZ</id>
        <id>HL70363_IZ</id>
        <id>HL70155_IZ</id>-->
    </NoValidation>

    <ValueSetDefinitions>
        <ValueSetDefinition BindingIdentifier="VS1" Name="Event type" Oid="" Version="1.5" Extensibility="Closed" Stability="Static">
            <ValueElement Value="1" CodeSystem="CodeSys" DisplayName="..." Usage="R"/>
            <ValueElement Value="2" CodeSystem="CodeSys" DisplayName="..." Usage="E"/>
            <ValueElement Value="3" CodeSystem="CodeSys" DisplayName="..." Usage="P"/>
        </ValueSetDefinition>

        <ValueSetDefinition BindingIdentifier="EmptyVS" Name="Event type" Oid="" Version="1.5" Extensibility="Closed" Stability="Static">
        </ValueSetDefinition>

        <ValueSetDefinition BindingIdentifier="BadVS" Name="Event type" Oid="" Version="1.5" Extensibility="Closed" Stability="Static">
            <ValueElement Value="1" CodeSystem="CodeSys" DisplayName="..." Usage="R"/>
            <ValueElement Value="1" CodeSystem="CodeSys" DisplayName="..." Usage="E"/>
        </ValueSetDefinition>
        <ValueSetDefinition BindingIdentifier="HL70003_IZ" Name="Event type" Oid="" Version="1.5">
            <ValueElement Value="V04" CodeSystem="HL70003" DisplayName="V04"/>
            <ValueElement Value="K11" CodeSystem="HL70003" DisplayName="K11"/>
            <ValueElement Value="Q11" CodeSystem="HL70003" DisplayName="Q11"/>
        </ValueSetDefinition>

        <ValueSetDefinition BindingIdentifier="HL70533_IZ" Name="Application Error Code" Oid="" Version="1.5" Stability="Dynamic" Extensibility="Closed">
            <ValueElement Value="1" CodeSystem="HL70533" DisplayName="Illogical Date error" Usage="R"/>
            <ValueElement Value="2" CodeSystem="HL70533" DisplayName="Invalid Date" Usage="R"/>
            <ValueElement Value="3" CodeSystem="HL70533" DisplayName="Illogical Value error" Usage="R"/>
            <ValueElement Value="4" CodeSystem="HL70533" DisplayName="Invalid value" Usage="R"/>
            <ValueElement Value="5" CodeSystem="HL70533" DisplayName="Table value not found" Usage="P"/>
            <ValueElement Value="6" CodeSystem="HL70533" DisplayName="Required observation missing" Usage="P"/>
        </ValueSetDefinition>
        <ValueSetDefinition BindingIdentifier="HL70301_IZ" Name="Universal ID type" Oid="" Version="1.5" Stability="Static" Extensibility="Closed">
            <ValueElement Value="OID" CodeSystem="HL70301" DisplayName="OID" Usage="R"/>
        </ValueSetDefinition>
        <ValueSetDefinition BindingIdentifier="HL70363_IZ" Name="Assigning Authority" Oid="" Version="1.5" Stability="Dynamic" Extensibility="Open">
            <ValueElement Value="AKA" CodeSystem="HL70363" DisplayName="ALASKA" Usage="R"/>
            <ValueElement Value="ALA" CodeSystem="HL70363" DisplayName="ALABAMA" Usage="R"/>
            <ValueElement Value="ARA" CodeSystem="HL70363" DisplayName="ARKANSAS" Usage="P"/>
            <ValueElement Value="ASA" CodeSystem="HL70363" DisplayName="AMERICAN SAMOA" Usage="P"/>
            <ValueElement Value="AZA" CodeSystem="HL70363" DisplayName="ARIZONA" Usage="E"/>
            <ValueElement Value="BAA" CodeSystem="HL70363" DisplayName="NEW YORK CITY" Usage="E"/>
            <ValueElement Value="CAA" CodeSystem="HL70363" DisplayName="CALIFORNIA" Usage="R"/>
            <ValueElement Value="CHA" CodeSystem="HL70363" DisplayName="CHICAGO" Usage="R"/>
            <ValueElement Value="COA" CodeSystem="HL70363" DisplayName="COLORADO" Usage="R"/>
            <ValueElement Value="CTA" CodeSystem="HL70363" DisplayName="CONNECTICUT" Usage="R"/>
            <ValueElement Value="DCA" CodeSystem="HL70363" DisplayName="DISTRICT OF COLUMBIA" Usage="R"/>
            <ValueElement Value="DEA" CodeSystem="HL70363" DisplayName="DELAWARE" Usage="R"/>
            <ValueElement Value="FLA" CodeSystem="HL70363" DisplayName="FLORIDA" Usage="R"/>
            <ValueElement Value="FMA" CodeSystem="HL70363" DisplayName="FED STATES MICRO" Usage="R"/>
            <ValueElement Value="GAA" CodeSystem="HL70363" DisplayName="GEORGIA" Usage="R"/>
            <ValueElement Value="GUA" CodeSystem="HL70363" DisplayName="GUAM" Usage="R"/>
            <ValueElement Value="HIA" CodeSystem="HL70363" DisplayName="HAWAII" Usage="R"/>
            <ValueElement Value="IAA" CodeSystem="HL70363" DisplayName="IOWA" Usage="R"/>
            <ValueElement Value="IDA" CodeSystem="HL70363" DisplayName="IDAHO" Usage="R"/>
            <ValueElement Value="ILA" CodeSystem="HL70363" DisplayName="ILLINOIS" Usage="R"/>
            <ValueElement Value="INA" CodeSystem="HL70363" DisplayName="INDIANA" Usage="R"/>
            <ValueElement Value="KSA" CodeSystem="HL70363" DisplayName="KANSAS" Usage="R"/>
            <ValueElement Value="KYA" CodeSystem="HL70363" DisplayName="KENTUCKY" Usage="R"/>
            <ValueElement Value="LAA" CodeSystem="HL70363" DisplayName="LOUISIANA" Usage="R"/>
            <ValueElement Value="MAA" CodeSystem="HL70363" DisplayName="MASSACHUSETTS" Usage="R"/>
            <ValueElement Value="MDA" CodeSystem="HL70363" DisplayName="MARYLAND" Usage="R"/>
            <ValueElement Value="MEA" CodeSystem="HL70363" DisplayName="MAINE" Usage="R"/>
            <ValueElement Value="MHA" CodeSystem="HL70363" DisplayName="REP MARS ISLANDS" Usage="R"/>
            <ValueElement Value="MIA" CodeSystem="HL70363" DisplayName="MICHIGAN" Usage="R"/>
            <ValueElement Value="MNA" CodeSystem="HL70363" DisplayName="MINNESOTA" Usage="R"/>
            <ValueElement Value="MOA" CodeSystem="HL70363" DisplayName="MISSOURI" Usage="R"/>
            <ValueElement Value="MPA" CodeSystem="HL70363" DisplayName="NO. MARIANA ISLAND" Usage="R"/>
            <ValueElement Value="MSA" CodeSystem="HL70363" DisplayName="MISSISSIPPI" Usage="R"/>
            <ValueElement Value="MTA" CodeSystem="HL70363" DisplayName="MONTANA" Usage="R"/>
            <ValueElement Value="NCA" CodeSystem="HL70363" DisplayName="NORTH CAROLINA" Usage="R"/>
            <ValueElement Value="NDA" CodeSystem="HL70363" DisplayName="NORTH DAKOTA" Usage="R"/>
            <ValueElement Value="NEA" CodeSystem="HL70363" DisplayName="NEBRASKA" Usage="R"/>
            <ValueElement Value="NHA" CodeSystem="HL70363" DisplayName="NEW HAMPSHIRE" Usage="R"/>
            <ValueElement Value="NJA" CodeSystem="HL70363" DisplayName="NEW JERSEY" Usage="R"/>
            <ValueElement Value="NMA" CodeSystem="HL70363" DisplayName="NEW MEXICO" Usage="R"/>
            <ValueElement Value="NVA" CodeSystem="HL70363" DisplayName="NEVADA" Usage="R"/>
            <ValueElement Value="NYA" CodeSystem="HL70363" DisplayName="NEW YORK STATE" Usage="R"/>
            <ValueElement Value="OHA" CodeSystem="HL70363" DisplayName="OHIO" Usage="R"/>
            <ValueElement Value="OKA" CodeSystem="HL70363" DisplayName="OKLAHOMA" Usage="R"/>
            <ValueElement Value="ORA" CodeSystem="HL70363" DisplayName="OREGON" Usage="R"/>
            <ValueElement Value="PAA" CodeSystem="HL70363" DisplayName="PENNSYLVANIA" Usage="R"/>
            <ValueElement Value="PHA" CodeSystem="HL70363" DisplayName="PHILADELPHIA" Usage="R"/>
            <ValueElement Value="PRA" CodeSystem="HL70363" DisplayName="PUERTO RICO" Usage="R"/>
            <ValueElement Value="RIA" CodeSystem="HL70363" DisplayName="RHODE ISLAND" Usage="R"/>
            <ValueElement Value="RPA" CodeSystem="HL70363" DisplayName="REPUBLIC PALAU" Usage="R"/>
            <ValueElement Value="SCA" CodeSystem="HL70363" DisplayName="SOUTH CAROLINA" Usage="R"/>
            <ValueElement Value="SDA" CodeSystem="HL70363" DisplayName="SOUTH DAKOTA" Usage="R"/>
            <ValueElement Value="TBA" CodeSystem="HL70363" DisplayName="SAN ANTONIO" Usage="R"/>
            <ValueElement Value="THA" CodeSystem="HL70363" DisplayName="HOUSTON" Usage="R"/>
            <ValueElement Value="TNA" CodeSystem="HL70363" DisplayName="TENNESSEE" Usage="R"/>
            <ValueElement Value="TXA" CodeSystem="HL70363" DisplayName="TEXAS" Usage="R"/>
            <ValueElement Value="UTA" CodeSystem="HL70363" DisplayName="UTAH" Usage="R"/>
            <ValueElement Value="VAA" CodeSystem="HL70363" DisplayName="VIRGINIA" Usage="R"/>
            <ValueElement Value="VIA" CodeSystem="HL70363" DisplayName="VIRGIN ISLANDS" Usage="R"/>
            <ValueElement Value="VTA" CodeSystem="HL70363" DisplayName="VERMONT" Usage="R"/>
            <ValueElement Value="WAA" CodeSystem="HL70363" DisplayName="WASHINGTON" Usage="R"/>
            <ValueElement Value="WIA" CodeSystem="HL70363" DisplayName="WISCONSIN" Usage="R"/>
            <ValueElement Value="WVA" CodeSystem="HL70363" DisplayName="WEST VIRGINIA" Usage="R"/>
            <ValueElement Value="WYA" CodeSystem="HL70363" DisplayName="WYOMING"/>
        </ValueSetDefinition>
        <ValueSetDefinition BindingIdentifier="HL70155_IZ" Name="Accept/Application acknowledgment conditions" Oid="" Version="1.5" Stability="Static" Extensibility="Open">
            <ValueElement Value="AL" CodeSystem="HL70155" DisplayName="Always" Usage="R"/>
            <ValueElement Value="NE" CodeSystem="HL70155" DisplayName="Never" Usage="R"/>
            <ValueElement Value="ER" CodeSystem="HL70155" DisplayName="Error/Reject conditions only" Usage="P"/>
            <ValueElement Value="SU" CodeSystem="HL70155" DisplayName="Successful completion only" Usage="E"/>
        </ValueSetDefinition>

        </ValueSetDefinitions>

</ValueSetLibrary >
